server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
    include-stacktrace: never

spring:
  application:
    name: course
  datasource:
    url: jdbc:mariadb://localhost:3306/switching
    username: didannguyen
    password: 17052002
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      max-lifetime: 2000000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true


course:
  auth:
    access:
      expire:
        minutes: 30
    refresh:
      expire:
        minutes: 10080
  key:
    public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnjUWe5tOjkg7/6Lbu8nN+a08tg46BHfuTqQ+yaEAOOfSvlPuGa2HHdGPMW3YdscZBqhupxkncdNRhOqZDxbbktLC97OWnKr3G8dsUvA77w3qV9OwR/LmdeU4BfYhvf5AIedGxB3S9sHhyZypjtuT4A/DZzZsIV4jCEjy12bt7DOsAkj5UYrc6gByGwF1ymsS4XOm9ZUdd+P6Zb4TpdNifQsCWxusnIOJtiDaf6GPfqoNBVcmG5nl5kBvVSQQybg9ckeUCGKTyyaSDYrI28RR7Np8Uh45TbHu5X8nShVIzODa+FzW+pYG12nOp7LLBlnlw+vX15t4u8YBX5lXNToE9QIDAQAB
    private: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCeNRZ7m06OSDv/otu7yc35rTy2DjoEd+5OpD7JoQA459K+U+4ZrYcd0Y8xbdh2xxkGqG6nGSdx01GE6pkPFtuS0sL3s5acqvcbx2xS8DvvDepX07BH8uZ15TgF9iG9/kAh50bEHdL2weHJnKmO25PgD8NnNmwhXiMISPLXZu3sM6wCSPlRitzqAHIbAXXKaxLhc6b1lR134/plvhOl02J9CwJbG6ycg4m2INp/oY9+qg0FVyYbmeXmQG9VJBDJuD1yR5QIYpPLJpINisjbxFHs2nxSHjlNse7lfydKFUjM4Nr4XNb6lgbXac6nsssGWeXD69fXm3i7xgFfmVc1OgT1AgMBAAECggEAIPCaPAW32zGIhn8U45pOr8nFTn2TUFtdK5QQe6AxQOfprdWhSUjjTU7U0tyVWZO2LvfyRAndd9phCnzi/eyLLpyB2huTBA8nsKm6sOEShYE+9ebeOPjGyay+V6Vp3JpbpYN3LT2tb1GqbnUXK6aluRznGS4QYPkt75tqrnUgnBFJRxnfPbAXcMMfbGeeP9EDV5G8pNi80RaVBb5D6gEqqMk8SofdgZWEtssHyIV/akULSL7VP3Tsyx4eJrBw+29/VVauziZzIcRj4LJ+KNZ4VbdxM05aj+YwajI4zpYE4Vr75Y2ZKZw8uXjQ5GRLM4geMUL8isx3YU7L5hbSvulfqQKBgQDQoJJIJRoYYbQYmuFU9zpu+8kZY7cpCfR+0M+EQqzE7Oj3aBCKFcsqNpYAnqLuK/cRq0g9mIM2i6M7JcJYsMYKNfwKSLUdTXufu+B0VKYChxLhp9NjDb7OIPJGzYsWMA5VOUpxFJdRWts/gaiDUNS9SvweUHVZhbRMzZyoYB+ZuQKBgQDCIaCo/hzzNnmlEwwyQ789jI8RlKyMjqDsWA+Nof1aH1am889M4WH++dFpAaNtzgHd2WWlSk8/7R8I+PVtQv6r1cK4UlZ3jS/+MD6vs1mXjdHxbkBG4c50GiGXaS+zDuR2dJOICPew0NhW+7r5pIambDQi1oqDkZBTK1+qOhPzHQKBgQC0/7opsVa0dH+lISoBZwRhKTzNND/B8QsXwt1m59mwd8Gec8B1rHa4xubY3siITchqoelo1xpvhjI1rIqyG5uVXESwP2gyZfitGnifNJladAmjkNDKjTBO8TKAzu6ubz7gHXZCKRUm1eaFcF3cn5ISMC4Ptso4wtEsGO6i/dIssQKBgCQrA7W4ckhV0+APZmxO9uhOsbEC1Arz38NovK0UixEpWYmNTwfxzcIlZQB9T6d7hBmDEU70Q0OTt/6B86fBnZUCJF8W6AkqAtEGyAcQERcNUxn6AnuyQjabT7rX3A0uLx5qpbnogc0te8Do8XLlVjjXW/dJpVDR4+O65v3eCC15AoGBALG5aWTazytOpLPriemSBeEgNzXbr1VI0Nk3Ej2el6hnCKnYUUCe/8ncR1fErskirwAp8M6igJUbKuUcdDmhdnm3sdS3u+pu2QyAcGumeHzKf9AxHMbrWMXSfp85Mg/huMKv8vsdGWXhO6cjwcUglk3Xx9TfBWmHbbIRupN/+ep9
  route:
    permit: /swagger-ui/**,/v3/api-docs/**,/actuator/**,/course/auth/login/**,/course/auth/signup/**,/course/images/**,/course/user/info/**

